language: objective-c
osx_image: xcode8
xcode_project: Postal.xcworkspace
xcode_scheme: Postal
before_install: 
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --no-build
